name: C/C++ CI

on: [push]

jobs:
 build: 
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@master
      
    - name: checkout google-test repo
      uses: actions/checkout@master
      with:
       repository: https://github.com/google/googletest.git
      
    - name: setup build env
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: build
      working-directory: containers_lib
      run: msbuild containers_lib.sln 
     
